# Autogenerated wrapper script for Matio_jll for x86_64-w64-mingw32
export libmatio

using Zlib_jll
using HDF5_jll
JLLWrappers.@generate_wrapper_header("Matio")
JLLWrappers.@declare_library_product(libmatio, "libmatio.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, HDF5_jll)
    JLLWrappers.@init_library_product(
        libmatio,
        "bin\\libmatio.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
