# Autogenerated wrapper script for Matio_jll for x86_64-apple-darwin
export libmatio

using Zlib_jll
using HDF5_jll
JLLWrappers.@generate_wrapper_header("Matio")
JLLWrappers.@declare_library_product(libmatio, "@rpath/libmatio.11.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, HDF5_jll)
    JLLWrappers.@init_library_product(
        libmatio,
        "lib/libmatio.11.0.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
